invenio:
  init: true  # initiates db, index, and admin roles
  hostname: "mex-stage.rki.de"
  default_users:
    mex@rki.de: "<placeholder>"
  existingSecret: "mex-invenio-secrets"
  create_fixtures: true
  extraConfig:
    INVENIO_SETTINGS_MODULE: "mex_invenio.config"
    MEX_IMPORT_OBJECT_KEY: "publisher.ndjson"
    # MEX import secrets now pulled from mex-invenio-secrets:
    # MEX_IMPORT_ENDPOINT_URL, MEX_IMPORT_AWS_KEY_ID, MEX_IMPORT_AWS_SECRET, 
    # MEX_IMPORT_BUCKET, MEX_IMPORT_EMAIL
    # INVENIO_MAIL_SERVER: "sandbox.smtp.mailtrap.io"
    # INVENIO_MAIL_PORT: "2525"
    # INVENIO_MAIL_USERNAME: "REPLACE-ME"
    # INVENIO_MAIL_PASSWORD: "REPLACE-ME"
    # INVENIO_MAIL_USE_SSL: "False"
    # INVENIO_MAIL_USE_TLS: "True"
  datacite:
    enabled: false

web:
  image: "ghcr.io/robert-koch-institut/mex-invenio:47464277938610aade49c54d060f33f860da5ead"
  imagePullPolicy: Always
  loadBalancerIP: "<placeholder>"
  annotations:
    loadbalancer.openstack.org/keep-floatingip: "true"
    #loadbalancer.openstack.org/proxy-protocol: "false"
    loadbalancer.openstack.org/load-balancer-address: "<placeholder>"
    loadbalancer.openstack.org/hostname: "mex-stage.rki.de"
  replicas: 5
  readinessProbe:
    failureThreshold: 5
    initialDelaySeconds: 10
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 1
  startupProbe:
    failureThreshold: 5
    initialDelaySeconds: 15
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 10

worker:
  image: "ghcr.io/robert-koch-institut/mex-invenio:47464277938610aade49c54d060f33f860da5ead"
  imagePullPolicy: Always
  replicas: 1

importjob:
  enabled: true
  imagePullPolicy: Always
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 2Gi

postgresql:
  enabled: false

# Provide these using --set argument, after pulling the secrets down from the vault:
postgresqlExternal: 
  hostname: "<placeholder>"
  port: 5432
  username: "<placeholder>"
  password: "<placeholder>"
  databaseName: "<placeholder>"

haproxy:
  enabled: false

flower:
  enabled: false

persistence:
  enabled: false
  storage_class: "csi-cinder-sc-retain"
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"

ingress:
  enabled: true
  class: "nginx"
  tlsSecretNameOverride: stage-tls
  annotations:
    kubernetes.io/ingress.class: "nginx"
    #cert-manager.io/cluster-issuer: "letsencrypt-production"
    #cert-manager.io/issue-temporary-certificate: "true"
    #acme.cert-manager.io/http01-edit-in-place: "true"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50G"
    nginx.ingress.kubernetes.io/whitelist-source-range: "<placeholder>"

clusterissuer:
  email: "mex@rki.de"
